export const MODULE_REGISTRY: Record<
  string,
  { title: string; description: string; icon: string; features: string[]; agentModuleKey?: string; agentLabel?: string }
> = {
  sales: {
    title: 'Ventes',
    description: 'Pipeline commercial, devis, prévisions et relances.',
    icon: 'VE',
    features: ['Pipeline Kanban', 'Devis', 'Objectifs', 'Relances'],
    agentModuleKey: 'sales',
    agentLabel: 'Ventes',
  },
  cms: {
    title: 'CMCMS',
    description: 'Gestion de contenu web et catalogues digitaux.',
    icon: 'CM',
    features: ['Pages & blocs', 'SEO', 'Multilingue', 'Publication planifiée'],
    agentModuleKey: 'cms',
    agentLabel: 'CMCMS',
  },
  pim: {
    title: 'PIPIM',
    description: 'Product Information Management — référentiel produits.',
    icon: 'PI',
    features: ['Fiches produit', 'Variantes', 'Médias', 'Canaux'],
    agentModuleKey: 'pim',
    agentLabel: 'PIPIM',
  },
  wms: {
    title: 'Stock / WMS',
    description: 'Inventaire, mouvements, alertes et commandes.',
    icon: 'ST',
    features: ['Stocks temps réel', 'Mouvements', 'Alertes', 'Commandes'],
    agentModuleKey: 'wms',
    agentLabel: 'Stock',
  },
  scm: {
    title: 'SCSC',
    description: 'Supply Chain — achats et fournisseurs.',
    icon: 'SC',
    features: ['Commandes fournisseurs', 'Lead times', 'Réappro'],
    agentModuleKey: 'scm',
    agentLabel: 'SCSC',
  },
  mrp: {
    title: 'MRMRP',
    description: 'Planification des besoins en matières.',
    icon: 'MR',
    features: ['Nomenclatures', 'OF', 'Capacités'],
    agentModuleKey: 'mrp',
    agentLabel: 'MRMRP',
  },
  bi: {
    title: 'Analytics / BI',
    description: 'KPI, rapports, prévisions et alertes anomalies.',
    icon: 'BI',
    features: ['Vues ventes/finance/clients', 'Alertes', 'Prévisions'],
    agentModuleKey: 'analytics',
    agentLabel: 'Analytics',
  },
  bpm: {
    title: 'Stratégie / BPM',
    description: 'Objectifs, risques, roadmap et décisions CEO.',
    icon: 'SG',
    features: ['OKR', 'Risques', 'Roadmap', 'Décisions'],
    agentModuleKey: 'strategie',
    agentLabel: 'Stratégie',
  },
  hcm: {
    title: 'RH / HCM',
    description: 'Équipes, rôles, congés et compétences.',
    icon: 'RH',
    features: ['Collaborateurs', 'Congés', 'Compétences'],
    agentModuleKey: 'rh',
    agentLabel: 'RH',
  },
  etl: {
    title: 'ETETL',
    description: 'Extract, Transform, Load — intégration de données.',
    icon: 'ET',
    features: ['Connecteurs', 'Pipelines', 'Monitoring'],
    agentModuleKey: 'etl',
    agentLabel: 'ETETL',
  },
  edi: {
    title: 'EDEDI',
    description: 'Échanges de documents structurés B2B.',
    icon: 'ED',
    features: ['EDIFACT', 'Factures électroniques', 'ASN'],
    agentModuleKey: 'edi',
    agentLabel: 'EDEDI',
  },
};
